.TH HEULPAD-NEW 1 "2024-12-10" "Heulpad 0.0.1" "HEULPAD MANUAL"
.SH NAME
heulpad-new \- terminal-based content management tool

.SH SYNOPSIS
.B heulpad status
[\fB\-v\fR|\fB\-\-version\fR]
[\fB\-h\fR|\fB\-\-help\fR]
.IR command " [" args... ]

.SH DESCRIPTION
.B heulpad status
is a command-line interface tool for managing notes and content

.SH OPTIONS
.TP
.BR \-v ", " \-\-version
Display version information

.TP
.BR \-h ", " \-\-help
Display a shortened help message

.SH HEULPAD COMMANDS
.TP
.BR new " [" name]
Create a new note with optional name

.TP
.BR enable " " plugin
Enable and install the specified plugin

.SH BUGS
Report bugs to: https://github.com/grabbiel/heulpad/issues

.SH SEE ALSO
Full documentation at: https://github.com/grabbiel/heulpad

